stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@mmb.irbbarcelona.org/gitlab/d.beltran.anadon/mdposit_client.git
    - cp bsc/host-config.js mdposit_client/src
    - cd mdposit_client
    - touch .env
    - npm install
    - npm run build
    - cp -r build ../build
  artifacts:
    paths:
      - build

deploy_job:
  stage: deploy
  script:
    - cd bsc
    - git config --global user.email "genis.bayarri@irbbarcelona.org"
    - git config --global user.name "Automatic CI/CD"
    - git clone https://oauth2:${GITLAB_ACCESS_TOKEN}@mmb.irbbarcelona.org/gitlab/gbayarri/mdposit-client-build.git
    - cd mdposit-client-build
    - cp -r ../../build ./bsc
    - cd bsc
    - zip -r build.zip build
    - git add build build.zip
    - git commit -m "Deploy new build for bsc"
    - git push origin main
  dependencies:
    - build_job